version: '3.4'
services:

  cms:
    image: misli/django-cms-site
    build: .
    depends_on:
      - db
      - memcached
    environment:
      SECRET_KEY: secretkey
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: ''
      DATABASE_NAME: django_cms
      DATABASE_PASSWORD: django_cms_password
      DATABASE_USER: django_cms
      MEMCACHED_LOCATION: memcached:11211
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./.ipython:/root/.ipython
      - ./data:/app/data
      - ./media:/app/htdocs/media
      - db:/var/run/mysqld

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: django_cms
      MYSQL_PASSWORD: django_cms_password
      MYSQL_ROOT_PASSWORD: django_cms_root_password
      MYSQL_USER: django_cms
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db:/var/run/mysqld
      - ./mysql:/var/lib/mysql

  memcached:
    image: memcached

volumes:
  db:
